hashtags_Colombia = [ "venecos en Colombia", "venecas en Colombia", "venezolanos en Colombia", "venezolanas en Colombia", "migrantes venezolanos Colombia"]
hashtags_Ecuador = [ "venecos en Ecuador", "venecas en Ecuador", "venezolanos en Ecuador", "venezolanas en Ecuador", "migrantes venezolanos Ecuador"]
hashtags_Peru = [ "venecos en Peru", "venecas en Peru", "venezolanos en Peru", "venezolanas en Peru", "migrantes venezolanos Peru", "venezolano Peru", "venezolana Peru"]
hashtags_Argentina = [ "venecos en Argentina", "venecas en Argentina", "venezolanos en Argentina", "venezolanas en Argentina", "migrantes venezolanos Argentina"]
hashtags_Chile = ["venecos Chile", "venecas Chile", "venezolanos Chile", "venezolanas Chile", "venezolano Chile", "venezolana Chile", "migrantes venezolanos Chile"]
hashtags_Panama = ["venecos Panama", "venecas Panama", "venezolanos Panama", "venezolanas Panama", "venezolano Panama", "venezolana Panama", "migrantes venezolanos Panama"]
hashtags_US = ["Venezuelans US", "Venezuelan migrants US", "Venezuelan immigrants US", "Venezuelan US"]