hashtags_Colombia = [ "venecos en Colombia", "venecas en Colombia", "venezolanos en Colombia", "venezolanas en Colombia"]
hashtags_Ecuador = [ "venecos en Ecuador", "venecas en Ecuador", "venezolanos en Ecuador", "venezolanas en Ecuador"]
hashtags_Peru = [ "venecos en Peru", "venecas en Peru", "venezolanos en Peru", "venezolanas en Peru"]
hashtags_Argentina = [ "venecos en Argentina", "venecas en Argentina", "venezolanos en Argentina", "venezolanas en Argentina"]
hashtags_Chile = ["venecos Chile", "venecas Chile", "venezolanos Chile", "venezolanas Chile", "venezolano Chile", "venezolana Chile"]
